### ISSUE TITLE
All props shifted by approx 1 map tile

### ISSUE THREAD

**Issue by originalfoo** [Quistar-LAB/PropAnarchy#2]
Log file:
[output_log.txt](https://github.com/Quistar-LAB/PropAnarchy/files/7794733/output_log.txt)

After changes on Dec 30th 2021 all the props in my city have suddenly shifted by approx 1 map tile, and are no longer selectable in Move It mod.

The height and angle of props seems to be correct, but they are shifted sideways on one axis.

![image](https://user-images.githubusercontent.com/1386719/147790423-5f2524d0-e6a8-48af-85e5-45983615c062.png)

I've also noticed that they seem to disappear depending on camera angle:

![image](https://user-images.githubusercontent.com/1386719/147790502-0ca49c80-50ae-424e-830d-399f995d7db7.png)

Change camera angle and they disappear:

![image](https://user-images.githubusercontent.com/1386719/147790513-1c7561c8-50b7-46b2-9c9c-868e09fd2aa3.png)

They seem to disappear at different angles, for example:

![image](https://user-images.githubusercontent.com/1386719/147790577-79d23e70-6a2c-4ced-a748-f1d55041cf4f.png)

![image](https://user-images.githubusercontent.com/1386719/147790592-402ff4df-12dc-4ffc-9a42-0737fb253389.png)

![image](https://user-images.githubusercontent.com/1386719/147790612-df62569b-83a8-4097-a7dd-83ec02fd5c71.png)

Recently updated mods:
![image](https://user-images.githubusercontent.com/1386719/147790813-b3e72fad-3107-4087-b768-4fce07e77a38.png)

**Comment by originalfoo** [comment]
As an interim workaround - maybe put a button in mod options that, when clicked, repositions the props by whatever offset they had?

The workaround on the mod comments of selecting all and adjust to terrain height is a major nigmare as I have thousands of props up on buildings (such as aircraft warning lights, shop signs, etc) it's going to be complete nightmare repositioning thousands of props.

**Comment by originalfoo** [comment]
Ah, just seen EML update with emergency button - will test now and report back.

**Comment by originalfoo** [comment]
Enabled in game but had no effect; assuming it needs enabling before loading save, it might be worth updating text of the button to make that clear to users.

**Comment by Quistar-LAB** [comment]
Yes, try enable before loading game

**Comment by originalfoo** [comment]
Ok, tried - props are still in same place, but now flattened to terrain and selectable.

![image](https://user-images.githubusercontent.com/1386719/147793236-e2c8707b-e4e1-4733-a0e3-7ccb637bc9c2.png)

Some are outside the map area entirely (light props on the right of image below):

![image](https://user-images.githubusercontent.com/1386719/147793274-0bbf16d1-0f11-4eb0-a6bf-49d7903ce74c.png)

I can't select those props with Move It as it's selection box is constrained to map size.

This gives some illustration of the extent of the issue I'm faced with:

![image](https://user-images.githubusercontent.com/1386719/147793370-25b758c8-bd27-4cdb-b53f-b925f82c5a4c.png)

I have over 26,000 hand-placed props which all need manual repositioning. :/

**Comment by Quistar-LAB** [comment]
Lemme see if I can find another way around this

**Comment by originalfoo** [comment]
Just read your comment on EML workshop page; will try save and load as described there and report back.

Might be worth highlighting that process in big quote box with h1 text on both PA and EML workshop descriptions.

Testing save/exit/load cycle now...

**Comment by Quistar-LAB** [comment]
Nono

**Comment by Quistar-LAB** [comment]
Don't! yet

**Comment by Quistar-LAB** [comment]
Ok reload game with version 1.0.0 again, with emergency checkbox enabled and start the procedure again, this time save

**Comment by originalfoo** [comment]
Ok, will try.

BTW, it's prolly best to show warning to users on main menu screen, before loading city, so they know what's happening. You can stop "Resume" (auto load last save) feature by setting `LauncherLoginData.instance.m_continue` to `false`, that way user will stay on main menu even if they chose "Resume" button on the Paradox Launcher app. They can still choose to load saves, etc., but at least they will know about potential issues. The OK button on displayed message can store that the warning has been viewed by user so it won't keep spamming on subsequent app launches.

**Comment by Quistar-LAB** [comment]
Yeah I know, but it'll probably take me another 2 hours just to get this warning message programmed

**Comment by originalfoo** [comment]
Hmm... doesn't look like it worked - with the button enabled, then loading save, will the props be in correct position when city loaded, or only after save + exit + reload? (each save I put under different file name so as not to overwrite old saves)

**Comment by Quistar-LAB** [comment]
Even with version 1.0.0?

**Comment by originalfoo** [comment]
With 1.0.0 - Enabled checkbox in EML settings, loaded save, and my cargo harbour props are still in the river:

![image](https://user-images.githubusercontent.com/1386719/147795558-9f8d1ea9-fcfb-4c0e-b365-bd3521c33fc5.png)

(BTW, the city I loaded was saved about 12-13 hours ago before the update that caused the problem as far as I can tell)

I'm about to save, exit, reload and will report back...

**Comment by originalfoo** [comment]
Hrm, that didn't go too well:

![image](https://user-images.githubusercontent.com/1386719/147795997-af226a3a-0a53-4acb-8ca7-d2f840809a6d.png)

Summary error text from "copy" button on that error panel:
```
The Mod C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\576327847 [EightyOne.dll] has caused an error [ModException]

Details:
System.InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper managed-to-native) object:__icall_wrapper_mono_object_castclass (object,intptr)
  at ColossalFramework.IO.DataSerializer.ReadObject[Data] (ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode, ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode) [0x00000] in <filename unknown>:0 
  at EightyOne.DataExtensions.AreaManagerDataExtension.OnLoadData () [0x00000] in <filename unknown>:0 
  at SerializableDataWrapper.OnLoadData () [0x00000] in <filename unknown>:0 
```

Full errror text from log file:
```
InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper managed-to-native) object:__icall_wrapper_mono_object_castclass (object,intptr)
  at ColossalFramework.IO.DataSerializer.ReadObject[Data] (ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode, ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode) [0x00000] in <filename unknown>:0 
  at EightyOne.DataExtensions.AreaManagerDataExtension.OnLoadData () [0x00000] in <filename unknown>:0 
  at SerializableDataWrapper.OnLoadData () [0x00000] in <filename unknown>:0 
Rethrow as ModException: The Mod C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\576327847 [EightyOne.dll] has caused an error

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
SerializableDataWrapper:OnLoadData()
SimulationManager:LateUpdateData(UpdateMode, Single, Single)
SimulationManager:Managers_LateUpdateData(UpdateMode, Single, Single)
<LoadSimulationData>c__IteratorB:MoveNext()
AsyncTask:Execute()
SimulationManager:SimulationStep()
SimulationManager:SimulationThread()
```

Log file:
[output_log.txt](https://github.com/Quistar-LAB/PropAnarchy/files/7794955/output_log.txt)

**Comment by Quistar-LAB** [comment]
Yep I noticed, please give EML workshop a quick resubscription

**Comment by Quistar-LAB** [comment]
BTW can you get on Discord. Its more convenient

**Comment by originalfoo** [comment]
Error still happening after unsub/resub EML

```
The Mod C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\576327847 [EightyOne.dll] has caused an error [ModException]

Details:
System.InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper managed-to-native) object:__icall_wrapper_mono_object_castclass (object,intptr)
  at ColossalFramework.IO.DataSerializer.ReadObject[Data] (ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode, ColossalFramework.IO.LegacyResolverHandler customResolver) [0x00000] in <filename unknown>:0 
  at ColossalFramework.IO.DataSerializer.Deserialize[Data] (System.IO.Stream stream, Mode mode) [0x00000] in <filename unknown>:0 
  at EightyOne.DataExtensions.AreaManagerDataExtension.OnLoadData () [0x00000] in <filename unknown>:0 
  at SerializableDataWrapper.OnLoadData () [0x00000] in <filename unknown>:0 
```

**Comment by Quistar-LAB** [comment]
Ok, please go back to a previous game save, and follow through the procedure again

**Comment by originalfoo** [comment]
Ok, trying with an autosave, and if that doesn't work I'll go back to much earlier 'forest' save.

![image](https://user-images.githubusercontent.com/1386719/147797046-23da4d55-5537-4dee-b248-857e4a9d0818.png)

**Comment by originalfoo** [comment]
Same issue:

![image](https://user-images.githubusercontent.com/1386719/147797534-6501ee31-f5ca-46ca-ae7c-2951ecfd2a34.png)

Going to try the much older `forest` save next.

**Comment by originalfoo** [comment]
Same issue with `forest` save. :(

Process I'm using:

1. Launch cities
    * Launcher app -> Play
2. Options > EML > Enable emergency button
    * It's showing EML version `1.0.0` on the options screen
3. Load a save (eg. `dec2021`, `AutoSave`, and most recently... `forest`)
4. City loads, but props are still in weird positions
5. Save city as `prop fuckery` (overwriting existing file)
6. Exit to desktop (note: I use `Instant Return to Desktop` mod, but doubt that makes any difference)
7. Launch game again + load city
    * Launcher app -> Resume
8. I get the 81 Tiles `cannot cast` error and the props are still in weird places

The `forest` save was made prior to `0.9.8` release as far as I can tell. The other saves (`dec2021` and `AutoSave`) were made after `0.9.8` release.

**Comment by Quistar-LAB** [comment]
That's really too bad... I tried getting around this issue, but for your situation, you'll have to go to a version before you started using EML

**Comment by originalfoo** [comment]
Would it not be possible to get a button that I can use in-game to just shift the position of the props?

It's not so much that props are 'floating' as many users report, the props are shifted sideways (appears to be different direction depending on map quadrant?)... if prop was at higher elevation originally, it will look like they are floating when it's at the shifted position as they will still be at original elevation. Moving back to original position = not floating any more.

If there was some way to just shift them back.... otherwise I'm losing about 2-3 days of city modifications. I can do it, of course,  but if there's any way of avoiding having to lose 2-3 days of changes....

**Comment by Quistar-LAB** [comment]
The thing is there's no way of telling the shift from the vector being loaded. I really hate to tell you this, but there's no other way for me to unsave the error introduced by previous EML version. I'm very sorry you had to lose 2~3 days of work.

**Comment by Quistar-LAB** [comment]
Please follow the procedure at https://github.com/Quistar-LAB/EManagersLib/releases to fix your issue

**Comment by originalfoo** [comment]
That worked!! :D 

I had to unsub `Customize It Extended` mod to get the 0.9.7 version to load without error; might be worth adding a note on that to releases page.
